"""Add phrase translation table

Revision ID: 32ebdf4f0e63
Revises: 91414d3cad83
Create Date: 2024-09-04 14:58:37.124113

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '32ebdf4f0e63'
down_revision: Union[str, None] = '91414d3cad83'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrase_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mansi_phrase', sa.String(), nullable=False),
    sa.Column('russian_phrase', sa.String(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrase_translation_id'), 'phrase_translation', ['id'], unique=False)
    op.create_index(op.f('ix_phrase_translation_mansi_phrase'), 'phrase_translation', ['mansi_phrase'], unique=False)
    op.drop_index('ix_phrasetranslation_id', table_name='phrasetranslation')
    op.drop_index('ix_phrasetranslation_mansi_phrase', table_name='phrasetranslation')
    op.drop_table('phrasetranslation')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrasetranslation',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('mansi_phrase', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('russian_phrase', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='phrasetranslation_pkey')
    )
    op.create_index('ix_phrasetranslation_mansi_phrase', 'phrasetranslation', ['mansi_phrase'], unique=False)
    op.create_index('ix_phrasetranslation_id', 'phrasetranslation', ['id'], unique=False)
    op.drop_index(op.f('ix_phrase_translation_mansi_phrase'), table_name='phrase_translation')
    op.drop_index(op.f('ix_phrase_translation_id'), table_name='phrase_translation')
    op.drop_table('phrase_translation')
    # ### end Alembic commands ###
