"""Initial migration for multiple tables

Revision ID: 4510ec1be88d
Revises: 5c994cba75a6
Create Date: 2024-09-05 12:24:07.753297

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4510ec1be88d'
down_revision: Union[str, None] = '5c994cba75a6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('phrase_translation', sa.Column('topic', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('phrase_translation', 'topic')
    # ### end Alembic commands ###
