"""Initial migration for multiple tables

Revision ID: 5c994cba75a6
Revises: f11ea4c5480a
Create Date: 2024-09-04 18:09:38.581590

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5c994cba75a6'
down_revision: Union[str, None] = 'f11ea4c5480a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mansi_word', sa.String(), nullable=False),
    sa.Column('russian_word', sa.String(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('word_translation')
    # ### end Alembic commands ###
