"""Add phrase translation table

Revision ID: 91414d3cad83
Revises: ddcb4afe1c99
Create Date: 2024-09-04 14:54:18.547567

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '91414d3cad83'
down_revision: Union[str, None] = 'ddcb4afe1c99'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('phrasetranslation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mansi_phrase', sa.String(), nullable=False),
    sa.Column('russian_phrase', sa.String(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_phrasetranslation_id'), 'phrasetranslation', ['id'], unique=False)
    op.create_index(op.f('ix_phrasetranslation_mansi_phrase'), 'phrasetranslation', ['mansi_phrase'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_phrasetranslation_mansi_phrase'), table_name='phrasetranslation')
    op.drop_index(op.f('ix_phrasetranslation_id'), table_name='phrasetranslation')
    op.drop_table('phrasetranslation')
    # ### end Alembic commands ###
