"""Initial migration for multiple tables

Revision ID: ad0a8db8f2a8
Revises: f05db19eeef2
Create Date: 2024-09-04 16:10:20.861902

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad0a8db8f2a8'
down_revision: Union[str, None] = 'f05db19eeef2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('suggested_phrase_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mansi_phrase', sa.String(), nullable=False),
    sa.Column('russian_phrase', sa.String(), nullable=False),
    sa.Column('context', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('suggested_word_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mansi_word', sa.String(), nullable=False),
    sa.Column('russian_word', sa.String(), nullable=False),
    sa.Column('part_of_speech', sa.String(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_index('ix_phrase_translation_id', table_name='phrase_translation')
    op.drop_index('ix_phrase_translation_mansi_phrase', table_name='phrase_translation')
    op.drop_column('phrase_translation', 'context')
    op.drop_index('ix_word_translation_id', table_name='word_translation')
    op.drop_index('ix_word_translation_mansi_word', table_name='word_translation')
    op.drop_column('word_translation', 'part_of_speech')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('word_translation', sa.Column('part_of_speech', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index('ix_word_translation_mansi_word', 'word_translation', ['mansi_word'], unique=False)
    op.create_index('ix_word_translation_id', 'word_translation', ['id'], unique=False)
    op.add_column('phrase_translation', sa.Column('context', sa.TEXT(), autoincrement=False, nullable=True))
    op.create_index('ix_phrase_translation_mansi_phrase', 'phrase_translation', ['mansi_phrase'], unique=False)
    op.create_index('ix_phrase_translation_id', 'phrase_translation', ['id'], unique=False)
    op.drop_table('suggested_word_translation')
    op.drop_table('suggested_phrase_translation')
    # ### end Alembic commands ###
