"""Add phrase translation table

Revision ID: f05db19eeef2
Revises: 32ebdf4f0e63
Create Date: 2024-09-04 15:02:15.346009

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f05db19eeef2'
down_revision: Union[str, None] = '32ebdf4f0e63'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('word_translation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mansi_word', sa.String(), nullable=False),
    sa.Column('russian_word', sa.String(), nullable=False),
    sa.Column('part_of_speech', sa.String(), nullable=True),
    sa.Column('definition', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_word_translation_id'), 'word_translation', ['id'], unique=False)
    op.create_index(op.f('ix_word_translation_mansi_word'), 'word_translation', ['mansi_word'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_word_translation_mansi_word'), table_name='word_translation')
    op.drop_index(op.f('ix_word_translation_id'), table_name='word_translation')
    op.drop_table('word_translation')
    # ### end Alembic commands ###
