"""Initial migration for multiple tables

Revision ID: f11ea4c5480a
Revises: ad0a8db8f2a8
Create Date: 2024-09-04 18:09:05.769389

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f11ea4c5480a'
down_revision: Union[str, None] = 'ad0a8db8f2a8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word_translation', 'russian_word',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('word_translation', 'russian_word',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
